spring:
  r2dbc:
    url: r2dbc:h2:mem:///usuariosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  cache:
    type: simple
logging:
  level:
    root: INFO
    com.nttdata.demo.agentes: INFO
